### ISSUE TITLE
Derivation of closed-form solution

### ISSUE THREAD

**Issue by rmndrs89** [boutrosrg/Machine-Learning#1]
Dear Boutros,

I was reading through Bishop's book, and in one of the first examples he performes polynomial curve fitting based on the error function defined by the sum of squares. I was starting to derive the equations myself, and then I wanted to check my derivations. Luckily I came across your blog and my derivations match with yours up to [**Eqn 12**](https://www.data-automaton.com/2018/01/09/nonlinear-regression/). 

However, now I would want to also derive the closed-form solution, and that is where I get stuck. More specifically how to go from **Eqn 14** to **Eqn 15**. How can I get rid of the summation over (_i_) from 1 to _N_?

Best,
Robbin
rmndrs89

P.S.: I am not sure if this is the place to discuss the derivations of the blog, but feel free to discard the issue if you feel like.

**Comment by boutrosrg** [comment]
Hi Robbin,
moving from Eq. 14 to Eq. 15 is straightforward! In the right-hand side, the bias w0 is repeated N times, therefore we move it outside the summation and multiplied it by N. Inside the summation, we left with regressors x(i) powered to polynomial p. As regressors x(i) powered 2 times to p in eq. 14, we replace the 2 summations with one sum and powered x(i) to 2p in eq. 15.

I also invite you to watch the related Youtube video (https://www.youtube.com/watch?v=dUa4ZovTeFc)

Hope this helps,
Boutros
